### ISSUE TITLE
Use error exit code rather than success when a device is not found. 

### ISSUE THREAD

**Issue by Spagett1** [pine64/blisp#29]
Would it be possible to get blisp to exit with return 1 instead of return 0 when it cant find a device? This seems more logical to me.

**Comment by River-Mochi** [comment]
@Spagett1  is trying to make  BLISP  work inside GUI Pineflash app  so  that  V2 pinecil people could potentially  have a GUI  to use.

Just last week I had to help 3 people who struggled with command line because  Terminals are very unfamiliar to them. not even knowing how to change to the folder that blisp is in.  Also the burden of finding the right IronOS file separately is hard for some people. 

Any help for  spagett1  would be awesome.  
PineFlash currently only works for Linux/MacOS  but it's a great start if we could get a Gui that auto allows picking language and fetches IronOS.

**Comment by Spagett1** [comment]
Hey robert, i was indeed wrong however that was me misdiagnosing the issue, what i should have said is that the program ends with a success code (1) not an error code (0). Not the message. 

 I edited my issue on GitHub to reflect this but it might not have updated since i see you are on email.

**Comment by River-Mochi** [comment]
@Spagett1 ,  Ralim said he will look at this  possibly tomorrow night.

**Comment by ShayBox** [comment]
It seems the Pine devs can't make up their mind, we had pinecil firmware updater in C++ using Qt which was cross-platform and worked pretty well, then they renamed it to pine64 updater and switched to Flutter which was Windows and macOS only, and pretty unusable in general, and now blisp which is command line only and doesn't even detect my device, original pinecil firmware updater still works :+1:

**Comment by Ralim** [comment]
Blisp is only for buffalo parts, namely bl70x and bl60x.

The Pine64 updater was a grand idea but sadly not enough developers interested to work on it (no paid Devs at pine, only volunteer, everyone spent their time complaining around missing features rather than trying to help add them). As such at the moment Pine64 updater only does the V1 pinecil.


As for why the C++ to flutter; mostly due to issues with the C++ one going forward as we looked to integrating other programming tools. But as mentioned before, not enough Dev time to get them finished being integrated.

**Comment by gamelaster** [comment]
@ShayBox as @Ralim says, PINE64 Updater don't have Pinecil V2 support, because I really don't have a time to do so.

The situation is, that it's not about that I can't made up my mind about what framework or platform to use, but it was specific evolution of tools.

(also, there is not such thing as Pine devs, Pine Store don't have software developers, all the software which is in this organization, is made by PINE64 Community, in their free time, for free. This also means that every contribution or feature ideas are always welcome.)

Pinecil Firmware Updater was tool, which was made in quite short time, to provide easy way of flashing Pinecil V1. It was made in Qt and C++, supported only few platforms, only Pinecil V1, and it just downloaded an firmware and executed dfu-util.

After some time, I decided that it might be good to have one tool for updating the PINE64 products, and also support another platforms in future (mainly Android and iOS), I decided to switch to Flutter, as it provides everything I needed, and I also have experienced with it.

Pine64 Updater although doesn't work that good as previous tool, because I tried something else, not spawning dfu-util, but covert dfu-util into dynamic library, and integrate it to tool, so we got better error handling and better progress status. This was also done, because platforms like iOS and Android wouldn't (most likely) support executing programs as we can do in Desktop OSes. Since I did the dfu-util conversion, it is not perfect, and it would need another XY hours to get it fully working properly, but sadly, I didn't had time for this.

Pinecil V2 arrived, and there was no good flashing tool at all, only weird official GUI tool, which didn't worked properly. Since I work with Bouffalo chips a lot, I made also blisp (it's only for Bouffalo tools, that's why it's named BouffaLo In System Programmer). Blisp is also not finished, because it needs huge rework to support new chips, that also means that library API of blisp is not stable, so if I would implement support to PINE64 Updater, I would need to rework it again after blisp API changes.

So, that's it. Feel free to contribute, as everything here is open-source.

**Comment by River-Mochi** [comment]
> original pinecil firmware updater still works 👍

original updater is for  Pinecil V1 which **only**.
BLISP for the newest V2 model of  Pinecil with a Green  Thumb grip and the newest  Bluetooth enabled BL706 MCU chip. it's not possible for you to use BLISP  if you dont have a Green thumbgrip Pinecil.

Follow the Instructions in Pinecil Wiki https://wiki.pine64.org/wiki/Pinecil_Firmware.  V1 and V2  which are completely different hardware,  Go to section of that article that is for  **Pinecil V1** and ignore all  sections for V2. 

- one can not use same flasher.  It has nothing to do with Pine devs not making up their minds. 
- Old Pinecil V1 people  - DFU  updater is used for that chip
- New post Aug1, 2022 V2 owners - BLISP is used bc the brain or MCU  is different   (think AMD versus Intel CPU). 

Spagett for his Pineflash app   supports the Pinecil V1   using DFU  under the hood,  he is adding  V2 support  by also including BLISP under the hood so to the user,  they will not notice. Technically though it's a wrapper for two different  flasher engines under the hood.   The Pine64_updater  only supports   the V1  bc it only has  DFU under the hood.  one could also just use  DFU  command line to update but then  need to fetch the IronOS  fw file separately.
